---
---

<br><br>

## High flow nasal oxygen during conscious sedation in the cardiac catheterisation laboratory: A randomized controlled trial

<div class = "row">
<div class = "col-md-3" align = "center">
<br><br>
<i class="fas fa-lungs fa-10x"></i>
</div>

<div class = "col-md-9">

> High flow nasal oxygen (HFNO) is increasingly regarded as a promising technology for oxygen delivery in critical care and anesthetic management. The 2018 guidelines from the American Society of Anesthesiology for procedural sedation stated that there is insufficient evidence regarding which methods of supplemental oxygen administration (e.g., nasal cannula, face mask, or specialized devices such as HFNO) are more effective. This trial will address this limitation in the evidence base specifically in regard to the efficacy of using HFNO during conscious sedation in the cardiac catheterisation laboratory.

</div>
</div>

<br>
<div align = "center">
## <i class="fa fa-search fa-lg"></i>  [View](HFNO/Protocol.html) the full trial protocol

<br><br>

## <i class="fa fa-tasks fa-lg"></i>  [Track](https://aconway.dev/hfno/) recruitment progress

<br><br>

## <i class="fa fa-info fa-lg"></i>  [Instructions](https://www.aaronconway.info/AA-instructions/#1) for using HFNO during the trial


<br><br>

## <i class="fa fa-info fa-lg"></i>  [View](SOP.html) Standard operating procedures the trial


</div>

<div
 class="canva-embed"
 data-design-id="DADen_OjGzk"
 data-height-ratio="2.5000"
 style="padding:250.0000% 5px 5px 5px;background:rgba(0,0,0,0.03);border-radius:8px;"
></div>
<script async src="https:&#x2F;&#x2F;sdk.canva.com&#x2F;v1&#x2F;embed.js"></script>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DADen_OjGzk&#x2F;view?utm_content=DADen_OjGzk&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">HFNO infographic</a> by <a href="https:&#x2F;&#x2F;www.canva.com&#x2F;AaronConway46?utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">Aaron Conway</a>
