---
---


<div align = "center">

# Temperature monitoring and management

</div>

<br>
<div class = "row">
<div class = "col-md-3" align = "center">
<br><br>
<i class="fas fa-temperature-frigid fa-8x"></i>
</div>
<div class = "col-md-9">

> Mild hypothermia (defined as temperature below 36°C) is considered an adverse effect of anaesthesia that should be avoided. Studies have shown that it increases post-operative complications and reduces patient satisfaction. Patients undergoing procedures in the cath lab are exposed to similar risks for perioperative hypotermia, including a low ambient room temperature and receiving medications that impair thermoregulation. Dr Conway's reearch in this area has revealed several significant findings.

</div>
</div>

## <i class="fa fa-angle-double-right fa-lg"></i> 1 in every 4 sedated patients were hypothermic (<36.0°C) 


Dr Conway conducted the first prospective [study](https://www.sciencedirect.com/science/article/pii/S1053077015005510) to identify the prevalence of hypothermia after procedures performed with sedation in the cath lab.


<br><br>


## <i class="fa fa-angle-double-right fa-lg"></i>  Forced air warming reduced risk of hypothermia by 25%

This [randomized controlled trial](https://heart.bmj.com/content/104/8/685) was published in the highly ranked cardiology journal *Heart*. The results support a change to current thermal management practices in an effort to reduce the incidence of inadvertent hypothermia (which is broadly viewed as an adverse effect of anaesthesia that should be avoided) and improve thermal comfort. 

<br><br>

## <i class="fa fa-angle-double-right fa-lg"></i> Forced air warming is cost-effective at a willingness to pay threshold of $34

Alongside the RCT, we conducted a [cost-effectiveness study](https://onlinelibrary.wiley.com/doi/full/10.1111/jan.13707) to determine how much an organization must be willing to pay for the use of forced air warming during sedation in the cath lab to be considered good value. We have also developed the interactive tool presented below that decision makers can use to estimate the probability that forced air warming would be cost‐effective at their institution.

 <iframe src="https://aaronconway.dev/thermalcomfort/" width="800" height="900" style="border: none;"></iframe>

 