---
title: "<center>2019 Summer Work Study Program</center>"
---



<div class = "row">
<div class = "col-md-3" align = "center">
<i class="fa fa-thermometer-half fa-8x"></i>
</div>

<div class = "col-md-9" align = "middle">
> <br><br>Zero heat flux thermometry: A systematic review and meta-analysis<br><br>

</div>
</div>
<br>
<div class = "row">
<div class = "col-md-3" align = "center">
## <i class="fa fa-bullseye-arrow fa-lg"></i> Goals
</div>
<div class = "col-md-9">
- Learn how to use [Covidence](https://www.covidence.org/home) to manage study selection, data extraction and risk of bias assessment
- Learn how to use the RStudio IDE (or RStudio Cloud)
- Learn how to use version control with RStudio
- Learn how to use R to perform meta-analysis of Bland-Altman method comparison studies
- Prepare a manuscript for publication
</div>
</div>
<br>
<div class = "row">
<div class = "col-md-3" align = "center">
## <i class="fa fa-tasks fa-lg"></i> Activities
</div>

### <i class="fa fa-angle-double-right fa-lg"></i> Complete the following [Datacamp](https://www.datacamp.com) courses
<div class = "col-md-9">
- Introduction to R (4 hours)
- Working with the RStudio IDE (Part 1) (3 hours)
- Chapter 2 - Version Control and Chapter 3 - Reporting of Working with the RStudio IDE (2 hours)
- Reporting with R Markdown (3 hours)
- Introduction to the Tidyverse (4 hours)

### <i class="fa fa-angle-double-right fa-lg"></i> Set-up R and RStudio

- Follow the instructions [here](https://rstudio.cloud/learn/guide) for RStudio Cloud

### <i class="fa fa-angle-double-right fa-lg"></i> Complete the following [Cochrane](https://training.cochrane.org/interactivelearning) courses
<div class = "col-md-9">
- Introduction to conducting systematic reviews
- Searching for studies
- Selecting studies and collecting data
- Introduction to study quality and risk of bias

### <i class="fa fa-angle-double-right fa-lg"></i> Systematic review

- Write a protocol for the systematic review and register at [PROSPERO](https://www.crd.york.ac.uk/prospero/)
- Devise search strategy
- Undertake literature search of databases and import results into Covidence
- Screen titles and abstracts
- Review full text of potentially relevant articles for inclusion
- Extract data and perform risk of bias assessment using QADAS-II
- Export data from Covidence and import to RStudio project
- Prepare a report using R Markdown to display the results and statistical code used for the analyses undertaken
- Commit and push to Github as progress is made
- Prepare a manuscript for publication



</div>
</div>

<br>
<div class = "row">
<div class = "col-md-3" align = "center">
### <i class="fa fa-info-circle fa-lg"></i> Resources
</div>

<div class = "col-md-9">
### <i class="fa fa-angle-double-right fa-lg"></i> General resources about R and version control

- #### Happy [Git](https://happygitwithr.com/) with R

- #### [Version control](https://bren.zendesk.com/hc/en-us/articles/360015826731-How-to-connect-RStudio-Cloud-with-Github) for RStudio Cloud

- #### <i class="fa fa-twitter fa-lg"></i> [#Rstats](https://twitter.com/search?q=%23rstats&src=typd)

### <i class="fa fa-angle-double-right fa-lg"></i> Systematic reviews

- #### [Example of meta-analysis of Bland-Altman method comparison studies](https://thorax.bmj.com/content/74/2/157.abstract)
- #### [Cochrane Handbook](https://training.cochrane.org/handbook)

</div>
</div>